# Travis-CI configuration file for VGMTrans

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:beineri/opt-qt541
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install gcc-4.9 g++-4.9; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - sudo apt-get install qt54base
  - source /opt/qt54/bin/qt54-env.sh
  - sudo apt-get install cmake libglib2.0-dev libfluidsynth-dev

before_script:
  - cd src/
  
script:
  - cmake CMakeLists.txt
  - make
