trigger:
- master

name: 
jobs:
- job: Windows_Legacy
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      x86:
        platform: Win32
        toolset: v142
        artifact-prefix: 'vgmtrans'
  steps:
  - task: VSBuild@1
    inputs:
      solution: 'VGMTrans_WTL.sln'
      platform: 'Win32'
      configuration: 'Release'
    displayName: 'Compile the VGMTrans solution'
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: $(artifact-prefix)-$(platform)
    